spring.application.name=andres-pizzeria

# Conexi�n directa a la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/pizzeria
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

# Dejamos que Spring maneje la creaci�n de tablas en desarrollo
spring.jpa.hibernate.ddl-auto=update